# "source": https://docs.docker.com/ci-cd/github-actions/

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # QEMU for arm docker image build.
      - name: Docker Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Docker meta arm64
        id: meta-arm64
        uses: docker/metadata-action@v3.7.0
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=arm64,onlatest=<true
            suffix=
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Build and push amd64
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot:buildcache-amd64
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot:buildcache-amd64,mode=max

      - name: Build and push arm64
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./
          file: ./Dockerfile-arm64
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta-arm64.outputs.tags }}
          labels: ${{ steps.meta-arm64.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot:buildcache-arm64
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/joplin-vieweb-certbot:buildcache-arm64,mode=max
